all:
  hosts:
    new_installation:
      ansible_host: 192.168.1.117
      ansible_python_interpreter: /usr/bin/python3
      ansible_env:
        TERM: "dumb"
        PROMPT_COMMAND: ""
        PS1: "$"
      ansible_ssh_common_args: "-o LogLevel=QUIET"
